// src/utils/Bookings.js

const data = [
    {
      bookingId: "BK001",
      customerName: "John Doe",
      propertyName: "Sunset Villa",
      agentName: "Agent A",
      bookingDate: "2023-08-10",
      amount: 1200,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK002",
      customerName: "Jane Smith",
      propertyName: "Mountain Retreat",
      agentName: "Agent B",
      bookingDate: "2023-08-12",
      amount: 1500,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK003",
      customerName: "Michael Johnson",
      propertyName: "Oceanfront Condo",
      agentName: "Agent C",
      bookingDate: "2023-08-14",
      amount: 2000,
      paymentStatus: "Refunded",
      bookingStatus: "Cancelled",
    },
    {
      bookingId: "BK004",
      customerName: "Sarah Lee",
      propertyName: "Urban Studio",
      agentName: "Agent D",
      bookingDate: "2023-08-16",
      amount: 800,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    },
    {
      bookingId: "BK005",
      customerName: "David Brown",
      propertyName: "Country House",
      agentName: "Agent E",
      bookingDate: "2023-08-18",
      amount: 2200,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK006",
      customerName: "Emma Wilson",
      propertyName: "Lakeview Cabin",
      agentName: "Agent F",
      bookingDate: "2023-08-20",
      amount: 1100,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK007",
      customerName: "Chris Green",
      propertyName: "Riverside Bungalow",
      agentName: "Agent G",
      bookingDate: "2023-08-22",
      amount: 2500,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK008",
      customerName: "Jessica Taylor",
      propertyName: "City Apartment",
      agentName: "Agent H",
      bookingDate: "2023-08-24",
      amount: 1800,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    },
    {
      bookingId: "BK009",
      customerName: "Nathan Adams",
      propertyName: "Beachfront Villa",
      agentName: "Agent I",
      bookingDate: "2023-08-26",
      amount: 1700,
      paymentStatus: "Refunded",
      bookingStatus: "Cancelled",
    },
    {
      bookingId: "BK010",
      customerName: "Olivia Martin",
      propertyName: "Penthouse Suite",
      agentName: "Agent J",
      bookingDate: "2023-08-28",
      amount: 3000,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK011",
      customerName: "Ethan Harris",
      propertyName: "Countryside Cottage",
      agentName: "Agent K",
      bookingDate: "2023-08-30",
      amount: 1200,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK012",
      customerName: "Sophia Lewis",
      propertyName: "Lakeside Mansion",
      agentName: "Agent L",
      bookingDate: "2023-09-01",
      amount: 1600,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    },
    {
      bookingId: "BK013",
      customerName: "Isabella Walker",
      propertyName: "Luxury Resort",
      agentName: "Agent M",
      bookingDate: "2023-09-03",
      amount: 2800,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK014",
      customerName: "Jackson Lee",
      propertyName: "Seaside Cottage",
      agentName: "Agent N",
      bookingDate: "2023-09-05",
      amount: 1400,
      paymentStatus: "Refunded",
      bookingStatus: "Cancelled",
    },
    {
      bookingId: "BK015",
      customerName: "Ava Scott",
      propertyName: "Mountain Lodge",
      agentName: "Agent O",
      bookingDate: "2023-09-07",
      amount: 2200,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK016",
      customerName: "Mason Young",
      propertyName: "Skyline View Apartment",
      agentName: "Agent P",
      bookingDate: "2023-09-09",
      amount: 2500,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    },
    {
      bookingId: "BK017",
      customerName: "Liam King",
      propertyName: "Desert Villa",
      agentName: "Agent Q",
      bookingDate: "2023-09-11",
      amount: 1900,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK018",
      customerName: "Zoe Martinez",
      propertyName: "Sunrise Resort",
      agentName: "Agent R",
      bookingDate: "2023-09-13",
      amount: 1500,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK019",
      customerName: "James Thomas",
      propertyName: "Hilltop House",
      agentName: "Agent S",
      bookingDate: "2023-09-15",
      amount: 2300,
      paymentStatus: "Refunded",
      bookingStatus: "Cancelled",
    },
    {
      bookingId: "BK020",
      customerName: "Mia White",
      propertyName: "Beach Resort",
      agentName: "Agent T",
      bookingDate: "2023-09-17",
      amount: 2000,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK021",
      customerName: "Logan Perez",
      propertyName: "Mountain Cabin",
      agentName: "Agent U",
      bookingDate: "2023-09-19",
      amount: 1400,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK022",
      customerName: "Aiden Gonzalez",
      propertyName: "City Loft",
      agentName: "Agent V",
      bookingDate: "2023-09-21",
      amount: 1600,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    },
    {
      bookingId: "BK023",
      customerName: "Amelia Rodriguez",
      propertyName: "Riverside Mansion",
      agentName: "Agent W",
      bookingDate: "2023-09-23",
      amount: 2100,
      paymentStatus: "Refunded",
      bookingStatus: "Cancelled",
    },
    {
      bookingId: "BK024",
      customerName: "Elijah Jackson",
      propertyName: "Cottage Retreat",
      agentName: "Agent X",
      bookingDate: "2023-09-25",
      amount: 1800,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK025",
      customerName: "Charlotte Harris",
      propertyName: "Lakeview Residence",
      agentName: "Agent Y",
      bookingDate: "2023-09-27",
      amount: 2000,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    },
    {
      bookingId: "BK026",
      customerName: "Henry Carter",
      propertyName: "Forest Lodge",
      agentName: "Agent Z",
      bookingDate: "2023-09-29",
      amount: 2500,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK027",
      customerName: "Grace Lee",
      propertyName: "Countryside Farmhouse",
      agentName: "Agent AA",
      bookingDate: "2023-10-01",
      amount: 1200,
      paymentStatus: "Refunded",
      bookingStatus: "Cancelled",
    },
    {
      bookingId: "BK028",
      customerName: "Isaiah Perez",
      propertyName: "Sunset Retreat",
      agentName: "Agent AB",
      bookingDate: "2023-10-03",
      amount: 2800,
      paymentStatus: "Paid",
      bookingStatus: "Confirmed",
    },
    {
      bookingId: "BK029",
      customerName: "Victoria Lewis",
      propertyName: "Luxury Mansion",
      agentName: "Agent AC",
      bookingDate: "2023-10-05",
      amount: 3500,
      paymentStatus: "Unpaid",
      bookingStatus: "Pending",
    },
    {
      bookingId: "BK030",
      customerName: "Benjamin Wilson",
      propertyName: "Beachside Condo",
      agentName: "Agent AD",
      bookingDate: "2023-10-07",
      amount: 2500,
      paymentStatus: "Paid",
      bookingStatus: "Completed",
    }
  ];
  
  export default data;
  