const data = [
  {
    name: "Alexander James Carter",
    opportunity: "Business Expansion Loan",
    status: "Active",
    memberId: "#OM123AA",
    date: "2024-03-18",
    tags: "Business",
  },
  {
    name: "Michael Anthony Johnson",
    opportunity: "Social Media Campaign",
    status: "Inactive",
    memberId: "#AT456BB",
    date: "2024-03-24",
    tags: "Design",
  },
  {
    name: "Sarah Miller Olivia",
    opportunity: "Website Redesign",
    status: "Active",
    memberId: "#EA789CC",
    date: "2024-01-22",
    tags: "Marketing",
  },
  {
    name: "Alexander Thompson Anderson",
    opportunity: "CRM Implementation",
    status: "Inactive",
    memberId: "#BH101DD",
    date: "2024-01-12",
    tags: "IT",
  },
  {
    name: "Emily Grace Walker",
    opportunity: "Lead Conversion Boost",
    status: "Active",
    memberId: "#FX202EE",
    date: "2024-02-02",
    tags: "Business",
  },
  {
    name: "Liam Benjamin Scott",
    opportunity: "Property Management System",
    status: "Active",
    memberId: "#HK303FF",
    date: "2024-02-15",
    tags: "IT",
  },
  {
    name: "Olivia Emma Jackson",
    opportunity: "Content Marketing Strategy",
    status: "Inactive",
    memberId: "#CN404GG",
    date: "2024-01-28",
    tags: "Marketing",
  },
  {
    name: "Noah Lucas Robinson",
    opportunity: "SEO Optimization",
    status: "Active",
    memberId: "#JK505HH",
    date: "2024-03-01",
    tags: "Design",
  },
  {
    name: "Ava Harper Martinez",
    opportunity: "Mobile App Launch",
    status: "Inactive",
    memberId: "#LM606II",
    date: "2024-02-20",
    tags: "IT",
  },
  {
    name: "William Henry Lopez",
    opportunity: "UX Redesign",
    status: "Active",
    memberId: "#NN707JJ",
    date: "2024-02-27",
    tags: "Design",
  },
  {
    name: "Sophia Evelyn Hall",
    opportunity: "Real Estate Listing Portal",
    status: "Active",
    memberId: "#AA808KK",
    date: "2024-01-10",
    tags: "Business",
  },
  {
    name: "James Oliver Young",
    opportunity: "Client Onboarding App",
    status: "Inactive",
    memberId: "#BB909LL",
    date: "2024-01-18",
    tags: "Marketing",
  },
  {
    name: "Isabella Lily Allen",
    opportunity: "Sales Dashboard Upgrade",
    status: "Active",
    memberId: "#CC010MM",
    date: "2024-02-04",
    tags: "Business",
  },
  {
    name: "Benjamin Samuel King",
    opportunity: "Market Analysis Tool",
    status: "Inactive",
    memberId: "#DD111NN",
    date: "2024-02-11",
    tags: "IT",
  },
  {
    name: "Mia Charlotte Wright",
    opportunity: "Automation Workflow",
    status: "Active",
    memberId: "#EE212OO",
    date: "2024-03-05",
    tags: "Marketing",
  },
  {
    name: "Lucas David Green",
    opportunity: "Digital Ad Strategy",
    status: "Inactive",
    memberId: "#FF313PP",
    date: "2024-03-15",
    tags: "Design",
  },
  {
    name: "Amelia Abigail Adams",
    opportunity: "Investor Pitch Deck",
    status: "Active",
    memberId: "#GG414QQ",
    date: "2024-01-25",
    tags: "Business",
  },
  {
    name: "Ethan Joseph Nelson",
    opportunity: "Referral Program Setup",
    status: "Inactive",
    memberId: "#HH515RR",
    date: "2024-03-11",
    tags: "Marketing",
  },
  {
    name: "Harper Ella Carter",
    opportunity: "Lead Generation Funnel",
    status: "Active",
    memberId: "#II616SS",
    date: "2024-02-14",
    tags: "IT",
  },
  {
    name: "Daniel Logan Rivera",
    opportunity: "Product Page Redesign",
    status: "Inactive",
    memberId: "#JJ717TT",
    date: "2024-03-02",
    tags: "Design",
  },
  {
    name: "Elizabeth Aria Cooper",
    opportunity: "Customer Success Platform",
    status: "Active",
    memberId: "#KK818UU",
    date: "2024-02-25",
    tags: "Business",
  },
  {
    name: "Matthew Jayden Flores",
    opportunity: "Performance Audit",
    status: "Inactive",
    memberId: "#LL919VV",
    date: "2024-01-30",
    tags: "IT",
  },
  {
    name: "Avery Scarlett Morris",
    opportunity: "Churn Analysis",
    status: "Active",
    memberId: "#MM020WW",
    date: "2024-03-07",
    tags: "Marketing",
  },
  {
    name: "Jack Dylan Rogers",
    opportunity: "Brand Refresh Campaign",
    status: "Inactive",
    memberId: "#NN121XX",
    date: "2024-03-13",
    tags: "Design",
  },
  {
    name: "Ella Grace Reed",
    opportunity: "New Agent Training",
    status: "Active",
    memberId: "#OO222YY",
    date: "2024-02-08",
    tags: "Business",
  },
  {
    name: "Sebastian Nathan Gray",
    opportunity: "Sales Performance Tracker",
    status: "Inactive",
    memberId: "#PP323ZZ",
    date: "2024-03-09",
    tags: "IT",
  },
  {
    name: "Chloe Victoria Price",
    opportunity: "Video Marketing Plan",
    status: "Active",
    memberId: "#QQ424AA",
    date: "2024-03-21",
    tags: "Marketing",
  },
  {
    name: "Henry Wyatt Barnes",
    opportunity: "Chatbot Integration",
    status: "Inactive",
    memberId: "#RR525BB",
    date: "2024-01-15",
    tags: "IT",
  },
  {
    name: "Scarlett Zoe Mitchell",
    opportunity: "Project Management Tool",
    status: "Active",
    memberId: "#SS626CC",
    date: "2024-02-12",
    tags: "Business",
  },
  {
    name: "Levi Gabriel Bailey",
    opportunity: "Realtor Mobile App",
    status: "Active",
    memberId: "#TT727DD",
    date: "2024-03-20",
    tags: "Design",
  },
];



export default data;